2021-04-29 09:03:10,176 ERROR: Exception on /explore [GET] [in /home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/routes.py", line 139, in explore
    posts = Post.query.order_by(Post_timestamp.desc()). all()
NameError: name 'Post_timestamp' is not defined
2021-04-29 09:06:43,611 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:07:20,696 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:07:24,559 ERROR: Exception on /explore [GET] [in /home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/routes.py", line 139, in explore
    posts = Post.query.order_by(Post_timestamp.desc()).all()
NameError: name 'Post_timestamp' is not defined
2021-04-29 09:07:54,817 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:20:12,114 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:40:55,102 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:42:41,060 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
